### ISSUE TITLE
Make header mobile responsive

### ISSUE THREAD

**Issue by Neno-Craig17** [PowerChangesLives/ThreeSixtyShot#16]

**Comment by PowerChangesLives** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Header to hamburger menu animation](https://trello.com/c/GkRfiZKv/20-header-to-hamburger-menu-animation)

**Comment by PowerChangesLives** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make header mobile responsive](https://trello.com/c/vHRhTVTF/21-make-header-mobile-responsive)
